//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGK_lynnEntities : DbContext
    {
        public SGK_lynnEntities()
            : base("name=SGK_lynnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Account> T_Account { get; set; }
        public virtual DbSet<T_Building> T_Building { get; set; }
        public virtual DbSet<T_Campus> T_Campus { get; set; }
        public virtual DbSet<T_Dept> T_Dept { get; set; }
        public virtual DbSet<T_Dorm> T_Dorm { get; set; }
        public virtual DbSet<T_Region> T_Region { get; set; }
        public virtual DbSet<T_Report> T_Report { get; set; }
        public virtual DbSet<T_Role> T_Role { get; set; }
        public virtual DbSet<T_Student> T_Student { get; set; }
        public virtual DbSet<T_SubReport> T_SubReport { get; set; }
        public virtual DbSet<vw_Account> vw_Account { get; set; }
        public virtual DbSet<vw_Building> vw_Building { get; set; }
        public virtual DbSet<vw_Dorm> vw_Dorm { get; set; }
        public virtual DbSet<vw_Region> vw_Region { get; set; }
        public virtual DbSet<vw_Student> vw_Student { get; set; }
        public virtual DbSet<vw_Report> vw_Report { get; set; }
        public virtual DbSet<vw_SubReport> vw_SubReport { get; set; }
        public virtual DbSet<T_Menu> T_Menu { get; set; }
        public virtual DbSet<vw_Menu> vw_Menu { get; set; }
        public virtual DbSet<T_RoleMenu> T_RoleMenu { get; set; }
        public virtual DbSet<vw_RoleMenu> vw_RoleMenu { get; set; }
    }
}
