//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Dorm
    {
        public string ID { get; set; }
        public string SSLD { get; set; }
        public Nullable<int> SSLC { get; set; }
        public string FJH { get; set; }
        public string SSLX { get; set; }
        public Nullable<int> ZSFY { get; set; }
        public Nullable<int> CWS { get; set; }
        public Nullable<int> KYCWS { get; set; }
        public string Sex { get; set; }
        public string DeptID { get; set; }
        public string Remark { get; set; }
        public string Bed_01 { get; set; }
        public string Bed_02 { get; set; }
        public string Bed_03 { get; set; }
        public string Bed_04 { get; set; }
        public string Bed_05 { get; set; }
        public string Bed_06 { get; set; }
        public string Bed_07 { get; set; }
        public string Bed_08 { get; set; }
        public string Bed_09 { get; set; }
        public string Bed_10 { get; set; }
    }
}
