//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Dorm
    {
        public string DormID { get; set; }
        public string BuildingID { get; set; }
        public Nullable<int> SSLC { get; set; }
        public string FJH { get; set; }
        public string SSLX { get; set; }
        public Nullable<int> ZSFY { get; set; }
        public Nullable<int> CWS { get; set; }
        public Nullable<int> KYCWS { get; set; }
        public string Sex { get; set; }
        public string DeptID { get; set; }
        public string Remark { get; set; }
        public string Bed_01 { get; set; }
        public string Bed_02 { get; set; }
        public string Bed_03 { get; set; }
        public string Bed_04 { get; set; }
        public string Bed_05 { get; set; }
        public string Bed_06 { get; set; }
        public string Bed_07 { get; set; }
        public string Bed_08 { get; set; }
        public string Bed_09 { get; set; }
        public string Bed_10 { get; set; }
        public string Building { get; set; }
        public string RegionID { get; set; }
        public string Region { get; set; }
        public string CampusID { get; set; }
        public string Campus { get; set; }
        public string Stu_01 { get; set; }
        public string Stu_02 { get; set; }
        public string Stu_03 { get; set; }
        public string Stu_04 { get; set; }
        public string Stu_05 { get; set; }
        public string Stu_06 { get; set; }
        public string Stu_07 { get; set; }
        public string Stu_08 { get; set; }
        public string Stu_09 { get; set; }
        public string Stu_10 { get; set; }
    }
}
