//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Report
    {
        public string ID { get; set; }
        public string AccountID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Num { get; set; }
        public string Reason { get; set; }
        public string AuditID { get; set; }
        public string RejectReason { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public string Name { get; set; }
        public string AuditName { get; set; }
    }
}
