//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SubReport
    {
        public string ID { get; set; }
        public string ReportID { get; set; }
        public string StudentID { get; set; }
        public string OutDormID { get; set; }
        public string InDormID { get; set; }
        public string PriceChanged { get; set; }
        public string StuName { get; set; }
        public string OutCampus { get; set; }
        public string OutRegion { get; set; }
        public string OutBuilding { get; set; }
        public string OutFJH { get; set; }
        public string InCampus { get; set; }
        public string InRegion { get; set; }
        public string InBuilding { get; set; }
        public string InFJH { get; set; }
    }
}
