//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Student
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string ClassName { get; set; }
        public string Sex { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string DeptID { get; set; }
        public string College { get; set; }
        public string Major { get; set; }
        public Nullable<int> Year { get; set; }
        public string StuStatus { get; set; }
        public string Status { get; set; }
        public string DormID { get; set; }
        public string Remark { get; set; }
        public string Dept { get; set; }
        public string Campus { get; set; }
        public string Region { get; set; }
        public string Building { get; set; }
        public string FJH { get; set; }
    }
}
